website/student/__init__.py
from flask import Blueprint

students = Blueprint('students', __name__)

from website.student import routes

website/student/routes.py
import json

from flask import Blueprint, render_template, flash, jsonify, request, url_for, redirect
from flask_login import login_required, current_user
from datetime import date, datetime
import googlemaps
import requests
from werkzeug.security import generate_password_hash

from website.form import *
from website.models import *
from website.adult import *
from website.views import *
from website.student import *
from website.user import *

API_KEY = "AIzaSyDLAnxto2DehvN5I5YdJuyBgEj7CZnX01A"
base_url = 'https://maps.googleapis.com/maps/api/geocode/json?'


@students.route('/offer')
@login_required
def offer():
    Offer.controltasksdate()
    q = Offer.query.filter(Offer.isAss == False, Offer.isClosed == False).all()

    def filtro(t):
        if t.__contains__(current_user):
            return False
        return True

    q1 = filter(filtro, q)

    return render_template("student/homeStud.html", user=current_user, tasks=q1)


@students.route('/apply/<task_id>', methods=['GET', 'POST'])
@login_required
def sendapplication(task_id):
    task = Offer.query.filter(Offer.id == task_id).first()
    if not current_user.controlapplication(task):
        flash('You already apply for this task', category='error')
        return redirect(url_for('views.home'))
    task.applicants.append(current_user)
    db.session.commit()
    return redirect(url_for('views.home'))


@students.route('/listapplications', methods=['GET', 'POST'])
@login_required  # every time we go to the home page
def listapplications():
    a = 0
    for off in current_user.getapplicationsopen():
        if not off.isAss:
            a = 1
            break

    return render_template("Student/listapplication.html", user=current_user, a=a)


@students.route('/deleteapplication/<task_id>')
def deleteapplication(task_id):
    t = Offer.query.filter(Offer.id == task_id).first()
    if t.scelta == current_user.id:
        flash('You have been chosen for this task, you cannot delete this task', category='error')
        return redirect(url_for('views.home'))

    t.applicants.remove(current_user)
    db.session.commit()
    flash('Application deleted!', category='success')
    return redirect(url_for('views.home'))


@students.route('/maps')
@login_required
def maps():
    q = Offer.query.filter(Offer.isAss == False, Offer.isClosed == False).all()

    def filtro(t):
        if t.__contains__(current_user):
            return False
        return True

    q1 = filter(filtro, q)

    configurations = {"locations": []}
    for offer in q1:
        configurations["locations"].append(offer.getdict())

    mapsApi = "AIzaSyDLAnxto2DehvN5I5YdJuyBgEj7CZnX01A"
    mapOptions = {"center": {"lat": 45.1161, "lng": 7.7420}, "fullscreenControl ": True, " mapTypeControl ": False,
                  "streetViewControl": False, "zoom": 2, "zoomControl": True, "maxZoom": 17}
    configurations['mapsApiKey'] = mapsApi
    configurations['mapOptions'] = mapOptions
    return render_template("Student/maps.html", user=current_user, CONFIGURATIONS=configurations, api=mapsApi,
                           mapsOptions=mapOptions)

website/templates/student/homeStud.html
{% extends "base.html" %}
{% block title %}Home Stud{% endblock %}
{% block content %}
    <br/>

    <div class="container" style="margin-bottom: 50vh">
        <div class="row">
            <h1 align="center">Find your perfect match</h1>
            <form method="POST">

                <br/>

                {% if tasks|length != 0 %}
                    <h2 class="m-2" align="center">List of open tasks</h2>
                    <table class="table table-hover">
                    <thead class="thead" style="color:whitesmoke; background:#2c3e50">
                    <tr>
                        <th scope="col">TASK</th>
                        <th scope="col">DESCRIPTION</th>
                        <th scope="col">APPLY</th>
                    </tr>
                    </thead>
                    {% for offer in tasks %}
                        <tbody>
                        <tr>
                            <th scope="row"><a style="color:darkblue"
                                               href={{ url_for('users.task', task_id=offer.id) }}>{{ offer.title }} </a>
                            </th>
                            <td>{{ offer.description }}</td>
                            <td>
                                <button type="button" style="background: #2c3e50" class="btn btn-secondary"><a
                                        style="color: white"
                                        href={{ url_for('students.sendapplication', task_id=offer.id) }}>APPLY</a>
                                </button>
                            </td>
                        </tr>
                        </tbody>
                    {% endfor %}
                {% else %}
                    <div class="row">
                        <div align="center" class="col-4">
                            <img class="img-fluid" alt="sorry" src="/static/images/pic/sorry.png"/>
                        </div>
                        <div class="col-8" style="margin-top:2em;">
                            <div class="button-55">We are sorry, but there are no task posted now. </br>
                                If you want to check your applications click <a style="color:darkblue" href={{ url_for('users.listapplications')}}>here</a>.
                                Otherwise come back later and check again to find your perfect match!
                            </div>
                        </div>
                    </div>
                {% endif %}
                </table>
            </form>
        </div>
    </div>

{% endblock %}

website/templates/student/listapplication.html
{% extends "base.html" %}
{% block title %}List of application{% endblock %}
{% block content %}
    <br/>

    <h1 align="center">YOUR APPLICATIONS</h1>
    <div class="container">
        <div class="row">

            <div class="col-5 p-4 m-2 col-page">
                <h2 align="center" class="mb-4">Pending Applications</h2>
                <table class="table table-hover">
                    {% set  l = user.getapplicationsopen() %}
                    {% if l %}
                        {% for offer in l %}
                            {% if offer.isAss==False %}
                                <thead class="thead-dark" style="color:whitesmoke; background:#2c3e50">
                                <tr>
                                    <th scope="col">Task</th>
                                    <th scope="col">Date</th>
                                    <th scope="col">Delete</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <th scope="row"><a style="color:darkblue"
                                                       href={{ url_for('users.task', task_id=offer.id) }}>{{ offer.title }}</a>
                                    </th>
                                    <td>{{ offer.date_task.strftime("%d/%m/%Y") }}</td>

                                    <td>
                                        <button type="button" data-toggle="modal" data-target="#deleteApplication"
                                                class="btn btn-outline-danger mx-4">
                                            Delete
                                        </button>
                                </tr>
                                </tbody>
                                <!-- Modal -->
                                <div class="modal fade" id="deleteApplication" tabindex="-1" role="dialog"
                                     aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Delete
                                                    application </h5>
                                            </div>
                                            <div class="modal-body">
                                                Are you sure you want to delete your application to this
                                                task?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary"
                                                        data-dismiss="modal">No
                                                </button>
                                                <button type="button" class="btn btn-primary">
                                                    <a style="color:white; text-decoration: none;"
                                                       href={{ url_for('students.deleteapplication', task_id=offer.id) }}>
                                                        Yes</a></button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                        {% if a != 1 %}
                            <div class="row">
                                <div align="center" class="col-4">
                                    <img class="img-fluid" alt="sorry" src="/static/images/pic/sorry.png"/>
                                </div>
                                <div class="col-8" style="margin-top:2em;">
                                    <div class="button-55">
                                        You have no pending tasks!
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% else %}
                        <div class="row">
                            <div align="center" class="col-4">
                                <img class="img-fluid" alt="sorry" src="/static/images/pic/sorry.png"/>
                            </div>
                            <div class="col-8" style="margin-top:2em;">
                                <div class="button-55">
                                    You have no pending tasks!
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </table>
            </div>


            <div class="col-1"></div>

            <!-- CLOSED APPLICATION -->

            <div class="col-5 p-4 m-2 col-page">
                <h2 align="center" class="mb-4">Closed Applications</h2>
                <!-- TASK WON-->
                <div class="row">
                    <div class="col">
                        <h4 align="left">Task won and reviewed</h4>
                        <table class="table table-hover">
                            {% set  l = user.taskwonperfandclosed() %}
                            {% if l %}
                                <thead class="thead-dark" style="color:whitesmoke; background:#2c3e50">
                                <tr>
                                    <th scope="col">Task</th>
                                    <th scope="col">Date</th>
                                </tr>
                                </thead>
                                {% for offer in l %}
                                    <tbody>
                                    <tr>
                                        <td>{{ offer.title }}</td>
                                        <td>{{ offer.date_task }}</td>
                                    </tr>
                                    </tbody>
                                {% endfor %}
                            {% else %}
                                <div class="row">
                                    <div class="col-" style="margin-top:2em;">
                                        <div class="button-task">
                                            We are sorry, you have no task won.
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        </table>
                    </div>
                </div>
                <!-- TASK WON and Performed-->
                <div class="row">
                    <h4 align="left">Task won to review</h4>
                    <div class="col">
                        <table class="table table-hover">
                            {% set  l = user.taskwonandperform() %}
                            {% if l %}
                                <thead class="thead-dark" style="color:whitesmoke; background:#2c3e50">
                                <tr>
                                    <th scope="col">Task</th>
                                    <th scope="col">Poster</th>
                                    <th scope="col">Review</th>
                                </tr>
                                </thead>

                                {% for offer in l %}
                                    <tbody>
                                    <tr>
                                        <td>{{ offer.title }}</td>
                                        <td>{{ offer.poster.first_name }}</td>
                                        {% if not offer.isClosed %}
                                            <td>
                                                <button type="button" class="btn btn-outline-danger mx-4 review-button">
                                                    <a style="color:black"
                                                       href={{ url_for('users.writereview', task_id=offer.id) }}>
                                                        Review</a>
                                                </button>
                                            </td>
                                            </tr>
                                            </tbody>

                                        {% endif %}

                                {% endfor %}
                            {% else %}
                                <div class="row">
                                    <div class="col-" style="margin-top:2em;">
                                        <div class="button-task">
                                            You have no task won to review!
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        </table>
                    </div>
                </div>

                <!-- TASK Lost-->
                <div class="row">
                    <div class="col">
                        <h4 align="left">Task lost</h4>
                        <table class="table table-hover">
                            {% set  l = user.tasklost() %}
                            {% if l %}
                                <thead class="thead-dark" style="color:whitesmoke; background:#2c3e50">
                                <tr>
                                    <th scope="col">Task</th>
                                    <th scope="col">Date</th>
                                </tr>
                                </thead>
                                {% for offer in l %}
                                    <tbody>
                                    <tr>
                                        <td>{{ offer.title }}</td>
                                        <td>{{ offer.date_task.strftime("%d/%m/%Y") }}</td>
                                    </tr>
                                    </tbody>
                                {% endfor %}
                            {% else %}
                                <div class="row">
                                    <div class="col-" style="margin-top:2em;">
                                        <div class="button-task">
                                            You have no tasks losted!
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        </table>
                    </div>
                </div>

            </div>

        </div>
    </div>

    <br/><br/>

{% endblock %}

website/templates/student/maps.html
{% extends "base.html" %} {% block scripts %}

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/handlebars/4.7.7/handlebars.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="static/css/locatorplus.css" rel="stylesheet">
    <!--bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="/static/locatorplus.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="/static/app.js"></script>

    <script type="text/javascript">
        function initMap() {
            new LocatorPlus({{ CONFIGURATIONS|tojson }});
        }

    </script>

    {% raw %}
    <script id="locator-result-items-tmpl" type="text/x-handlebars-template">
        {{#each locations}}
        <li class="location-result" data-location-index="{{index}}">
            <button class="select-location">
                <h4 class="task-name">{{title}}</h4>
            </button>
            <h5 class="task-address">{{address1}} - {{address2}}</h5>
            {{#if travelDistanceText}}
            <div class="distance">{{travelDistanceText}}</div>
            {{/if}}
            <button type="button" style="background:#2c3e50; color:white; padding:0 12px 0 12px; " class="pick-task"
                    onClick="window.location.href = '/task/'+{{ task_id }}">Choose this Task
            </button>
        </li>
        {{/each}}
    </script>
    {% endraw %}

{% endblock %}

{% block title %}Locator{% endblock %}

{% block content %}
    <br/>

    <div id="map-container">
        <!--locatior-->

        <div id="locations-panel">
            <div id="locations-panel-list">
                <header>
                    <h1 class="search-title">
                        <img src="https://fonts.gstatic.com/s/i/googlematerialicons/place/v15/24px.svg"/>
                        Find a location near you
                    </h1>
                    <div class="search-input">
                        <input id="location-search-input" placeholder="Enter your address or zip code">
                        <div id="search-overlay-search" class="search-input-overlay search">
                            <button id="location-search-button">
                                <img class="icon"
                                     src="https://fonts.gstatic.com/s/i/googlematerialicons/search/v11/24px.svg"
                                     alt="Search"/>
                            </button>
                        </div>
                    </div>
                </header>
                <div class="section-name" id="location-results-section-name">
                    All locations
                </div>
                <div class="results">
                    <ul id="location-results-list"></ul>
                </div>
            </div>
        </div>

        <!--mappa-->
        <div id="map"></div>
    </div>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDLAnxto2DehvN5I5YdJuyBgEj7CZnX01A&callback=initMap&libraries=places,geometry&solution_channel=GMP_QB_locatorplus_v4_cABD"
            async defer></script>


{% endblock %}

website/templates/student/task.html
{% extends "base.html" %}
{% block title %}Apply for task{% endblock %}
{% block content %}


    <div class="container task-container" style="margin-bottom: 50vh">
        <div class="row task-row">
            <div class="col-12">
                <h1 align="left" class="task-title">{{ taskscelta.title }}</h1>
                <h3>Posted by <span class="task-owner"><a style="color:darkblue"
                                                          href="{{ url_for('users.showreviews', user_id=taskscelta.id_adult, task_id='0') }}">{{ taskscelta.poster.first_name }}{{ taskscelta.poster.surname }}</a></span>
                </h3>
                <h4>Location: {{ taskscelta.address }}, Torino</h4>
                <h6>This task will be performed on {{ taskscelta.date_task.strftime("%d/%m/%Y") }}</h6>
                <h6>The application deadline is: {{ taskscelta.dateexpire.strftime("%d/%m/%Y") }}</h6>
                <div class="task-description">
                    {{ taskscelta.description }}
                </div>
                <h6>This task will pay: {{ taskscelta.amount }} €</h6>
                {% if btn ==True %}
                    <br/>
                    <br/>
                    <div align="center">
                        <button type="button" style="background: #2c3e50" class="btn btn-primary btn-lg"><a
                                style="color: white"
                                href={{ url_for('students.sendapplication', task_id=taskscelta.id) }}>APPLY</a>
                        </button>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}