website/adult/__init__.py
from flask import Blueprint

adults = Blueprint('adults', __name__)

from website.adult import routes

website/adult/routes.py
import json

from flask import Blueprint, render_template, flash, jsonify, request, url_for, redirect
from flask_login import login_required, current_user
from datetime import date, datetime
import googlemaps
import requests
from werkzeug.security import generate_password_hash
from website.form import *
from website.models import *
from website.adult import *
from website.views import *
from website.student import *
from website.user import *

API_KEY = "AIzaSyDLAnxto2DehvN5I5YdJuyBgEj7CZnX01A"
base_url = 'https://maps.googleapis.com/maps/api/geocode/json?'


@adults.route('/posttask', methods=['GET', 'POST'])
@login_required
def posttask():
    form = PosttaskForm()
    if request.method == 'POST':
        address = request.form['location']
        if not address:
            flash('Insert a valid address', category='error')
            return redirect(url_for('adults.posttask'))
        datatask = request.form['date']
        amount = request.form['amount']

        locality = request.form['locality']
        administrative_area_level_1 = request.form['administrative_area_level_1']
        postal_code = request.form['postal_code']
        country = request.form['country']
        dateexpire = request.form['dateexpire']

        dt = datetime.strptime(datatask, '%Y-%m-%d')
        dtexp = datetime.strptime(dateexpire, '%Y-%m-%d')
        params = {
            'key': API_KEY,
            'address': address + locality + administrative_area_level_1 + postal_code + country
        }
        r = requests.get(base_url, params=params).json()
        geometry = r['results'][0]['geometry']['location']
        lat = geometry['lat']
        lng = geometry['lng']
        placeId = r['results'][0]['place_id']
        today = datetime.now()
        if dt < today or dtexp < today or dt < dtexp:
            form.date.data = ''
            flash('The date inserted cannot be before the current date', category='error')
            return redirect(url_for('adults.posttask'))
        else:
            title = form.tasktitle.data
            description = form.taskdescription.data

            if len(title) < 1:
                flash('Title is too short!', category='error')
            else:
                a = {"title": title, "address1": address, "address2": "Torino", "coords": {"lat": lat, "lng": lng},
                     "placeId": placeId}
                new_offer = Offer(title=title, description=description, date_task=dt, dateexpire=dtexp,
                                  id_adult=current_user.id, lat=lat,
                                  lng=lng, placeId=placeId, amount=amount, address=address)
                db.session.add(new_offer)
                db.session.commit()
                flash('Task posted!', category='success')
                return redirect(url_for('views.home'))
    else:
        return render_template("adult/posttask.html", user=current_user, form=form)


@adults.route('/choosestud/<task_id>/<stud_id>', methods=['GET', 'POST'])
@login_required
def choosestud(task_id, stud_id):
    task1 = Offer.query.filter(Offer.id == task_id).first()
    if not Offer.controldate(task1):
        flash('Too late the task is closed', category='error')
        return redirect(url_for('views.home'))
    task1.scelta = stud_id
    task1.isAss = True
    db.session.commit()

    return redirect(url_for('views.home'))


@adults.route('/taskpending')
def taskpending():
    pending = []
    for task in current_user.tasks:
        if task.isAss and task.isClosed == False:
            pending.append(task)
        if task.isAss == False and task.isPerf == True:
            pending.append(task)

    return render_template("adult/taskspending.html", user=current_user, pending=pending)


@adults.route('/deletetask/<task_id>')
def deletetask(task_id):
    t = Offer.query.filter(Offer.id == task_id).first()
    if t.applicants:
        flash('There are already applications for this task you cannot delete this task', category='error')
        return redirect(url_for('views.home'))
    db.session.delete(t)
    db.session.commit()
    flash('Task deleted!', category='success')
    return redirect(url_for('views.home'))

website/templates/adult/chooseStud.html
{% extends "base.html" %}
{% block title %}Student choice{% endblock %}
{% block content %}

    <div class="container task-container" style="margin-bottom: 20vh">
        <div class="row task-row">
            <div class="col-12">
                <h1>Task name: {{ taskscelta.title }}</h1>
                <div>Task description: {{ taskscelta.description }}</div>
                <div>
                    <br/>
                    <br/>
                    {% if taskscelta.applicants %}
                        <h3>Applicants:</h3>
                        {% for applicant in taskscelta.applicants %}
                            <div align="left">
                                <a style="color:darkblue"
                                   href={{ url_for('users.showreviews', user_id=applicant.id, task_id=taskscelta.id) }}>{{ applicant.first_name }} {{ applicant.surname }}</a>
                                <div align="right">
                                    <button type="button" style="background: #2c3e50" class="btn btn-primary btn-lg"><a
                                            style="color: white"
                                            href={{ url_for('adults.choosestud', task_id=taskscelta.id, stud_id=applicant.id) }}>Choose
                                        this student </a></button>
                                </div>
                            </div>
                            <br/>
                        {% endfor %}
                    {% else %}
                        <div class="row">
                            <div align="center" class="col-4">
                                <img class="img-fluid" alt="sorry" src="/static/images/pic/sorry.png"/>
                            </div>
                            <div class="col-8" style="margin-top:2em;">
                                <div class="button-55">
                                    We are sorry there are no applicants yet!
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>

            </div>
        </div>
    </div>

{% endblock %}

website/templates/adult/homeAdult.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}

    <br/>

    <div class="container" style="margin-bottom: 50vh">
        <div class="row">
            <h1 align="center">YOUR POSTED TASK</h1>

            {% if user.gettasksopen()|length != 0 %}
                <h2 class="m-2" align="center">List of open tasks</h2>
                <table class="table">
                <thead class="thead" style="color:whitesmoke; background:#2c3e50">
                <tr>
                    <th scope="col">TASK</th>
                    <th scope="col">DESCRIPTION</th>
                    <th scope="col">APPLICANTS</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                {% for offer in user.gettasksopen() %}
                    <tbody>
                    <tr>
                        {% if not offer.isAss %}
                            <th scope="row"><a style="color:darkblue"
                                               href={{ url_for('users.task', task_id=offer.id) }}>{{ offer.title }}</a>
                            </th>
                            <td>{{ offer.description }}</td>
                            <td align="center"> {{ offer.applicants|length }}</td>
                            <td>
                                <button type="button" style="background: #2c3e50" class="btn btn-secondary"><a
                                        style="color: white" href={{ url_for('adults.deletetask', task_id=offer.id) }}>DELETE
                                    TASK</a></button>
                            </td>
                        {% endif %}
                    </tr>
                    </tbody>
                {% endfor %}
            {% else %}
                <div class="row">
                    <div align="center" class="col-4">
                        <img class="img-fluid" alt="sorry" src="/static/images/pic/sorry.png"/>
                    </div>
                    <div class="col-8" style="margin-top:2em;">
                        <div class="button-55">You have not posted a task yet! </br>
                            Click <a style="color:darkblue" href={{ url_for('users.posttask') }}>here</a> if you want to
                            post your first task.
                        </div>

                    </div>
                </div>
            {% endif %}
            </table>
        </div>
    </div>

    <br/>
    <br/>

{% endblock %}

website/templates/adult/posttask.html
{% extends "base.html" %}
{% block title %}Post Tasks{% endblock %}
{% block content %}
    <br/>

    <div class="container" style="margin-bottom: 10vh">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <form class="postatask-form" method="POST" style="margin:0;">
                    <h1 align="left"> Post Task </h1>
                    <div align="justify"> Tell us what are you looking for and we
                        will do our best to find it!
                    </div>
                    <br/>

                    <div class="form-group">
                        {{ form.tasktitle.label }}
                        {{ form.tasktitle(class = 'form-control') }}
                        {% for error in form.tasktitle.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        {{ form.taskdescription.label }}
                        {{ form.taskdescription(class = 'form-control') }}
                        {% for error in form.taskdescription.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        {{ form.amount.label }}
                        {{ form.amount(class = 'form-control') }}
                        {% for error in form.amount.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>

                    <div class="form-group">
                        <div style="display:inline;">
                            <div>
                                {{ form.date.label(class= "dropdwown") }}
                                <button type="button" class="icon-info-sign" style="border:none; background: none;"
                                        data-toggle="modal" data-target="#typeModal"></button>
                                {{ form.date(class = 'form-control') }}
                                {% for error in form.date.errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                            </div>

                            <!-- trigger for type modal-->


                            <!-- Modal for type-->
                            <div class="modal fade" id="typeModal" tabindex="-1" role="dialog"
                                 aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalCenterTitle">Date</h5>
                                        </div>
                                        <div class="modal-body">
                                            Insert the date in which the task has to be performed.
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Ok!
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="form-group">
                        <div style="display:inline;">
                            <div>
                                {{ form.dateexpire.label(class= "dropdwown") }}
                                <button type="button" class="icon-info-sign" style="border:none; background: none;"
                                        data-toggle="modal" data-target="#expirationModal"></button>
                                {{ form.dateexpire(class = 'form-control') }}
                                {% for error in form.dateexpire.errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                            </div>
                            <div style="position:relative; float:left">
                                <!-- trigger for type modal-->


                                <!-- Modal for type-->
                                <div class="modal fade" id="expirationModal" tabindex="-1" role="dialog"
                                     aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalCenterTitle">Expiration
                                                    date</h5>
                                            </div>
                                            <div class="modal-body">
                                                Insert the date within which you want to know who will perform the task.
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                                    Ok!
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div class="panel">
                            <br/>
                            <div>
                                <img class="sb-title-icon"
                                     src="https://fonts.gstatic.com/s/i/googlematerialicons/location_pin/v5/24px.svg"
                                     alt="">
                                <span class="sb-title">Address Selection</span>
                            </div>
                            <div>
                                <input class="inputAddress" type="text" placeholder="Address" id="location"
                                       name="location"/>
                                <input class="inputAddress" type="text" placeholder="Apt, Suite, etc (optional)"/>
                                <input class="inputAddress" type="text" placeholder="City" id="locality"
                                       name="locality"/>
                                <div class="half-input-container">
                                    <input type="text" class="half-input" placeholder="State/Province"
                                           id="administrative_area_level_1" name="administrative_area_level_1"/>
                                    <input type="text" class="half-input" placeholder="Zip/Postal code" id="postal_code"
                                           name="postal_code"/>
                                </div>
                                <input class="inputAddress" type="text" placeholder="Country" id="country"
                                       name="country"/>
                            </div>
                            <br/>
                        </div>
                        <div align="center">
                            {{ form.submit(class='btn btn-success m-2') }}
                            {{ form.hidden_tag() }}
                        </div>
                    </div>
                </form>
                <script
                        type="text/javascript"
                        src="{{ url_for('static', filename='app.js') }}"
                ></script>
                <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDLAnxto2DehvN5I5YdJuyBgEj7CZnX01A&libraries=places&callback=initMap&solution_channel=GMP_QB_addressselection_v1_cAC"
                        async defer></script>
            </div>
            <div class="col-sm-12 col-md-6">
                <img class="img-fluid" style="max-height: 85%; min-width: 100%" src="/static/images/pic/dogsitter.png"/>
            </div>
        </div>
    </div>

{% endblock %}

website/templates/adult/taskspending.html
{% extends "base.html" %}
{% block title %}Task to be performed{% endblock %}
{% block content %}

    <br/>
    <h1 align="center">YOUR TASKS</h1>

    <div class="container" style="margin-bottom: 50vh">
        <div class="row">

            <div class="col-5 p-4 m-2 col-page">
                <h2 align="center" class="mb-4">Open Tasks</h2>
                <table class="table table-hover">
                    {% set  l = user.gettasksopen() %}
                    {% if l %}
                        {% for offer in l %}
                            {% if offer.isAss==False %}
                                <thead class="thead-dark" style="color:whitesmoke; background:#2c3e50">
                                <tr>
                                    <th scope="col">Task</th>
                                    <th scope="col">Date</th>
                                    <th scope="col">Delete</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <th scope="row"><a style="color:darkblue"
                                                       href={{ url_for('users.task', task_id=offer.id) }}>{{ offer.title }}</a>
                                    </th>
                                    <td>{{ offer.date_task.strftime("%d/%m/%Y") }}</td>
                                    <td>
                                        <button type="button" class="btn btn-outline-danger mx-4"><a
                                                class="delete-button"
                                                href={{ url_for('adults.deletetask', task_id=offer.id) }}> Delete</a>
                                        </button>
                                    </td>
                                </tr>
                                </tbody>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <div class="row">
                            <div align="center" class="col-4">
                                <img class="img-fluid" alt="sorry" src="/static/images/pic/sorry.png"/>
                            </div>
                            <div class="col-8" style="margin-top:2em;">
                                <div class="button-55">
                                    You have no pending tasks!
                                </div>
                            </div>
                        </div>
                    {% endif %}

                </table>
            </div>

            <!--//////////////////////////////////////////-->

            <div class="col-1"></div>
            <div class="col-5 p-4 m-2 col-page">
                <h2 align="center" class="mb-4">Closed Tasks</h2>

                <div class="row">
                    <div class="col">
                        <h4 align="left">Closed and reviewed</h4>
                        <table class="table table-hover">
                            {% set  l = user.gettaskclosed() %}
                            {% if l %}
                                <thead class="thead-dark" style="color:whitesmoke; background:#2c3e50">
                                <tr>
                                    <th scope="col">Task</th>
                                    <th scope="col">Date</th>
                                </tr>
                                </thead>
                                {% for offer in l %}
                                    <tbody>
                                    <tr>
                                        <td>{{ offer.title }}</td>
                                        <td>{{ offer.date_task.strftime("%d/%m/%Y") }}</td>
                                    </tr>
                                    </tbody>
                                {% endfor %}
                            {% else %}
                                <div class="row">
                                    <div class="col-" style="margin-top:2em;">
                                        <div class="button-task">
                                            You have no closed and reviewed tasks!
                                        </div>
                                    </div>
                                </div>
                            {% endif %}

                        </table>
                    </div>
                </div>


                <div class="row">
                    <h4 align="left">Assigned to review</h4>
                    <div class="col">
                        <table class="table table-hover">
                            {% set  l = user.gettasksAssnotPerf() %}
                            {% if l %}
                                <thead class="thead-dark" style="color:whitesmoke; background:#2c3e50">
                                <tr>
                                    <th scope="col">Task</th>
                                    <th scope="col">Performer</th>
                                    <th scope="col">Review</th>
                                </tr>
                                </thead>

                                {% if pending|length != 0 %}
                                    {% for offer in pending %}
                                        <tbody>
                                        <tr>
                                            <td>{{ offer.title }}</td>
                                            <td>{{ offer.performer.first_name }}</td>
                                            {% if offer.isAss==True and offer.isPerf==False %}
                                                <td>
                                                    <button type="button"
                                                            class="btn btn-outline-danger mx-4 review-button"><a
                                                            style="color:black"
                                                            href={{ url_for('users.writereview', task_id=offer.id) }}>
                                                        Review</a>
                                                    </button>
                                                </td>
                                                </tr>
                                                </tbody>
                                            {% endif %}
                                    {% endfor %}
                                {% endif %}
                            {% else %}
                                <div class="row">
                                    <div class="col-" style="margin-top:2em;">
                                        <div class="button-task">
                                            You have no tasks assigned to review!
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        </table>
                    </div>
                </div>


                <div class="row">
                    <div class="col">
                        <h4 align="left">Expired, but not performed</h4>
                        <table class="table table-hover">
                            {% set  l = user.gettaskexpired() %}
                            {% if l %}
                                <thead class="thead-dark" style="color:whitesmoke; background:#2c3e50">
                                <tr>
                                    <th scope="col">Task</th>
                                    <th scope="col">Date</th>
                                </tr>
                                </thead>
                                {% for offer in l %}
                                    <tbody>
                                    <tr>
                                        <td>{{ offer.title }}</td>
                                        <td>{{ offer.date_task.strftime("%d/%m/%Y") }}</td>
                                    </tr>
                                    </tbody>
                                {% endfor %}
                            {% else %}
                                <div class="row">
                                    <div class="col-" style="margin-top:2em;">
                                        <div class="button-task">
                                            You have no tasks expired!
                                        </div>
                                    </div>
                                </div>
                            {% endif %}

                        </table>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <br/><br/>
{% endblock %}