website/auth.py
# Authentication
from datetime import datetime, timedelta

from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash

from . import db
from .form import LoginForm, SignupForm
from .models import *

auth = Blueprint('auth', __name__)


# We sad clearly that we can accept get and post requests

@auth.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if request.method == 'POST' and form.validate_on_submit():
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                if user.type == 'student':
                    return redirect(url_for('views.home'))
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')
    return render_template("User/login.html", user=current_user, form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign_up', methods=['GET', 'POST'])
def sign_up():
    form = SignupForm()
    if request.method == 'POST' and form.validate_on_submit():

        email = request.form.get('email')
        name = request.form.get('name')
        surname = request.form.get('surname')
        password = request.form.get('password')
        description = request.form.get('description')
        passwordconf = request.form.get('passwordconf')
        type = request.form.get('type')

        user = User.query.filter_by(email=email).first()
        new_user = User
        if type == 'student':
            new_user = Student(email=email, password=generate_password_hash(password, method='sha256'), first_name=name,
                               surname=surname, type=type, description=description)
        elif type == 'adult':
            new_user = Adult(email=email, password=generate_password_hash(password, method='sha256'),
                             first_name=name, surname=surname, type=type, description=description)
        db.session.add(new_user)
        db.session.commit()
        flash('Account created!', category='success')
        login_user(new_user, remember=True)
        if new_user.type == 'student':
            return redirect(url_for('students.offer'))

        return redirect(url_for('views.home'))
    return render_template("User/sign_up.html", user=current_user, form=form)


def riempidb():
    studenti = [
        {'name': "Giacomo", 'surname': "Bertazzolo",
         'description': "I am a studente in IT engineering. I can help you with your computer and all of your electronic devices."},
        {'name': "Valeria", 'surname': "Liuni",
         'description': "I am a student in Engineering and Management at Politecnico di Torino. I love animals and I am ready to help you with them!"},
        {'name': "Caterina", 'surname': "Nassi",
         'description': "I am a student in Education and Formation. I love babies, and I am usually available at the last minute. "},
        {'name': "Oliviero", 'surname': "Vidoni",
         'description': ""},
    ]

    adulti = [
        {'name': "Maria", 'surname': "Bianchi",
         'description': "I am a Manager in a consultancy firm. I have a 4 lovely dogs and I am always looking for someone who can help me with them."},
        {'name': "Paolo", 'surname': "Giorgi",
         'description': "I am a grandfather with 4 amazing nephews. They cannot bear anymore my problems with technology and for this reason I decided to join this community."},
        {'name': "Mario", 'surname': "Rossi",
         'description': "I am a single father whit 3 beautiful children. It may happen that I cannot find someone who can help me with them, especially when there are last minute calls at work."},
    ]

    tasks = [
        {'titolo': "My lovely pet ",
         'descrizione': "I need help with my lovey pet. I'm looking for someone who can take care of her for the afternoon. She is really sweet and docile.",
         'date': "2022-04-23", 'lat': "45.058427", 'lng': "7.655138", 'placeId': "ChIJbZ33QSFtiEcR3Yr-cxhtfDQ",
         'address': "Corso Lione 40"},
        {'titolo': "My PC is not working",
         'descrizione': "I am looking for someone who can fix my computer. My internet connection does not work, can you help me?",
         'date': "2022-05-17", 'lat': "45.07215960121708", 'lng': "7.681296735921444",
         'placeId': "ChIJ-w5Ey3NtiEcRizrB7W-hDNI", 'address': "Via Barbaroux 20"},
        {'titolo': "My grandmother",
         'descrizione': "I am looking for someone who can keep company to my gradmother because she is very lonely.",
         'date': "2022-05-18", 'lat': "45.0602789482421", 'lng': "7.659934143334852",
         'placeId': "ChIJx4qR9SJtiEcRqjxf1yPr6KI", 'address': "Via Marco Polo 38"},
        {'titolo': "My house is a mess!",
         'descrizione': "Hy everyone! I am looking for someone who can help me with my messy house. I am an artist and I have a lot of things in my house that I want to get rid off. Please come and help me! ",
         'date': "2022-04-19", 'lat': "45.074369423709875", 'lng': "7.6562016089387965",
         'placeId': "ChIJXbcpbQJtiEcRayf8ZeGWbPI", 'address': "Corso Ferrucci 12"},
        {'titolo': "Out of town",
         'descrizione': "I am out of town this weekend and my pet sitter is sick! I am looking for a last minute help with my two cats. Please, I am desperate!",
         'date': "2022-03-19", 'lat': "45.031349418202346", 'lng': "7.650670868351874",
         'placeId': "ChIJk67CatsSiEcRwIxAtahQVQg", 'address': "Via Nizza 129"},
        {'titolo': "Moving out",
         'descrizione': "Hello! I am moving out of my house and all of my friends are busy. I am looking for someone that can help me. I have a lot of books and they may be heavy. Thank you!",
         'date': "2022-02-24", 'lat': "45.06489699683761", 'lng': "7.630211069168476",
         'placeId': "ChIJu6nBNJVsiEcRjUReMrrGsg0", 'address': "Via Monginevro 3"},
        {'titolo': "After-school activities",
         'descrizione': "I am looking for someone who can help my children of 12 years old with some math exercises.",
         'date': "2022-03-28", 'lat': "45.07150270339428", 'lng': "7.6755482647576425",
         'placeId': "ChIJbQiBvnJtiEcRuxTkED8C4I8", 'address': "Via Cernaia 8"},
        {'titolo': "Looking for a gardening expert",
         'descrizione': "I am looking for someone who has a passion in gardening that can help me with my plants.",
         'date': "2022-06-28", 'lat': "45.062928866175696", 'lng': "7.701314035921153",
         'placeId': "ChIJ-f-CvJ5yiEcR9YkHqilhGP8", 'address': "Via Umberto Cosmo 6"}
    ]

    ids = {5, 6, 7, 5, 6, 7, 5}

    for studente in studenti:
        mail = studente['name'].lower() + studente['surname'].lower() + '@mail.com'
        user_db = Student(first_name=studente['name'],
                          surname=studente['surname'],
                          email=mail,
                          description=studente['description'],
                          password=generate_password_hash('1234567890', method='sha256'),
                          type='student')
        db.session.add(user_db)
        db.session.commit()

    for adulto in adulti:
        mail = adulto['name'].lower() + adulto['surname'].lower() + '@mail.com'
        user_db = Adult(first_name=adulto['name'],
                        surname=adulto['surname'],
                        email=mail,
                        description=adulto['description'],
                        password=generate_password_hash('1234567890', method='sha256'),
                        type='adult')
        db.session.add(user_db)
        db.session.commit()

    for task in tasks:
        b = 5
        dt = datetime.strptime(task['date'], '%Y-%m-%d')
        de = dt - timedelta(days=4)
        us = User.query.get(b)
        b += 1

        new_offer = Offer(title=task['titolo'], description=task['descrizione'], date_task=dt, amount=10, dateexpire=de,
                          id_adult=us.id, lat=task['lat'], lng=task['lng'], placeId=task['placeId'],
                          address=task['address'])
        db.session.add(new_offer)
        db.session.commit()

    applicant = User.query.get(1)
    offer1 = Offer.query.get(1)
    offer1.applicants.append(applicant)
    applicant2 = User.query.get(2)
    offer1.applicants.append(applicant2)
    print offer1.applicants
    db.session.commit()

website/user/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__)

from website.user import routes

website/user/routes.py
import json

from flask import Blueprint, render_template, flash, jsonify, request, url_for, redirect
from flask_login import login_required, current_user
from datetime import date, datetime
import googlemaps
import requests
from werkzeug.security import generate_password_hash

from website.form import *
from website.models import *
from website.adult import *
from website.views import *
from website.student import *
from website.user import *

API_KEY = "AIzaSyDLAnxto2DehvN5I5YdJuyBgEj7CZnX01A"
base_url = 'https://maps.googleapis.com/maps/api/geocode/json?'


@users.route('/writereview/<task_id>', methods=['GET', 'POST'])
@login_required
def writereview(task_id):
    if request.method == 'POST':
        form = ReviewForm()
        title = form.reviewtitle.data
        description = form.reviewdescription.data
        date = datetime.now()

        t = Offer.query.filter(Offer.id == task_id).first()
        if current_user.type == 'adult':
            t.isPerf = True
            new_review = Review(title=title, text=description, date=date, id_reviewer=current_user.id,
                                id_reviewed=t.scelta,
                                task_id=t.id)
        # aggiungere reviews all'user
        else:
            t.isClosed = True
            new_review = Review(title=title, text=description, date=date, id_reviewer=current_user.id,
                                id_reviewed=t.id_adult,
                                task_id=t.id)
        db.session.add(new_review)
        db.session.commit()

        return redirect(url_for('views.home'))

    else:
        form = ReviewForm()
        t = Offer.query.filter(Offer.id == task_id).first()
        return render_template("user/review.html", user=current_user, taskscelta=t, form=form)


@users.route('/showreviews/<user_id>/<task_id>', methods=['GET', 'POST'])
@login_required
def showreviews(user_id, task_id):
    if current_user.type == 'adult':
        reviewed = User.query.filter(User.id == user_id).first()
        var = current_user.reviewsreceived
        recensioni = Review.query.filter(Review.id_reviewed == user_id).all()
        return render_template("user/listofreview.html", user=current_user, recensioni=recensioni, reviewed=reviewed,
                               task_id=task_id)
    else:
        reviewed = User.query.filter(User.id == user_id).first()
        recensioni = Review.query.filter(Review.id_reviewed == user_id).all()
        return render_template("user/listofreview.html", user=current_user, recensioni=recensioni, reviewed=reviewed,
                               task_id=0)


@users.route('/about_us')
def about_us():
    return render_template("about_us.html", user=current_user)


@users.route('/account')
def account():
    return render_template("User/account.html", user=current_user)


@users.route('/posttask')
def posttask():
    return render_template("User/posttask.html", user=current_user)


@users.route('/listapplications')
def listapplications():
    return render_template("User/listapplications.html", user=current_user)


@users.route('/personalreviews')
def personalreviews():
    return render_template("User/personalreviews.html", user=current_user)


@users.route("/updateaccount", methods=['GET', 'POST'])
@login_required
def updateaccount():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.email = form.email.data
        current_user.name = form.name.data
        db.session.commit()
        flash('Succesfully updated informations', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.email.data = current_user.email
        form.name.data = current_user.name
    # manca il render template capire cosa serve
    return render_template(user=current_user, form=form)


@users.route('/task/<task_id>', methods=['GET', 'POST'])
@login_required
def task(task_id):
    if current_user.type == 'student':
        t = Offer.query.filter(Offer.id == task_id).first()
        # controllo se ho gia applicato cosi so se posso far comparire il bottone oppure no
        btn = True
        if current_user in t.applicants:
            btn = False
        return render_template("Student/task.html", user=current_user, taskscelta=t, btn=btn)
    else:
        t = Offer.query.filter(Offer.id == task_id).first()
        return render_template("adult/chooseStud.html", user=current_user, taskscelta=t)

website/templates/user/account.html
{% extends "base.html" %}
{% block title %}Personal settings{% endblock %}
{% block content %}
    <br/>
    <h1 align="center">Your profile</h1>

    <div class="container" style="margin-bottom: 50vh">
        <div class="row">
            <div align="center" class="col-3 profile-box m-3 p-3">
                <div class="row">
                    <div class="col-2">
                        {% if user.type=='student' %}
                            <img align="left" width="60" height="60" alt="usertype"
                                 src="/static/images/pic/student.png"/>
                        {% elif user.type=='adult' %}
                            <img align="left" width="60" height="60" alt="usertype"
                                 src="/static/images/pic/worker.png"/>
                        {% endif %}
                    </div>
                    <div class="col-8">
                        <h3 class="px-2">{{ user.first_name }} {{ user.surname }}</h3>
                    </div>
                    <div class="row">
                        <p class="px-3">{{ user.email }}</p>
                        <h3>About me:</h3>
                        <div style="text-align:left;">
                            {% if user.description != None %}
                                <div class="profileDescription">
                                    {{ user.description }}
                                </div>
                            {% else %}
                                <div class="row">
                                    <div align="center" class="col" style="margin-top:2em;">
                                        <div class="button-55">
                                            You did not add a description.
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    </div>

                </div>
            </div>

            <div class="col-8 reviews-box m-3">

                <!--personal reviews-->
                <h1 align="left" class="p-2">What people tell: </h1>
                {% if user.reviewsreceived|length !=0 %}
                    {% for recens in user.reviewsreceived %}
                        <div class="box-review">
                            <h2>Reviewed by: <span class="review-author"> {{ recens.author.first_name }}</span></h2>
                            <h4 class="review-title">{{ recens.title }}</h4>
                            {{ recens.text }}
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="row">
                        <div align="center" class="col" style="margin-top:2em;">
                            <div class="button-55">
                                You have no review!
                            </div>
                        </div>
                    </div>
                {% endif %}

            </div>
        </div>
    </div>

{% endblock %}

website/templates/user/listofreview.html
{% extends "base.html" %}
{% block title %}List of review of users{% endblock %}

{% block styles %}
{% endblock %}

{% block content %}
    <br/>
    <h1 align="center">About {{ reviewed.first_name }} {{ reviewed.surname }}</h1>



    <div class="container" style="margin-bottom: 50vh">
        <div class="row">
            <div align="center" class="col-3 profile-box m-3 p-3">
                <div style="display:inline">
                    <div style="position:relative; float:left">
                        {% if user.type=='student' %}
                            <img align="left" width="60" height="60" alt="usertype"
                                 src="/static/images/pic/worker.png"/>
                        {% elif user.type=='adult' %}
                            <img align="left" width="60" height="60" alt="usertype"
                                 src="/static/images/pic/student.png"/>
                        {% endif %}
                    </div>
                    <div style="position:relative; float:left;">
                        <h4 style="padding-top:8px;">User description</h4>
                    </div>
                </div>
                <br/><br/><br/>
                <div style="margin:2px 0px 0px 0px">
                    <div align="left">
                        {% if reviewed.description != None %}
                            <div class="profileDescription">
                                {{ reviewed.description }}
                            </div>
                        {% else %}
                            We are sorry! The user has no description.
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="col-8 reviews-box m-3">

                <h1 align="left" class="p-2">REVIEWS </h1>
                {% if reviewed.reviewsreceived|length !=0 %}
                    {% for recens in reviewed.reviewsreceived %}
                        <div class="box-review">
                            <h2>Reviewed by: <span class="review-author"> {{ recens.author.first_name }}</span></h2>
                            <h4 class="review-title">{{ recens.title }}</h4>
                            {{ recens.text }}

                        </div>
                    {% endfor %}
                {% else %}
                    <div class="row">
                        <div align="center" class="col" style="margin-top:2em;">
                            <div class="button-task">
                                There are no review for this user.
                            </div>
                        </div>
                    </div>
                {% endif %}


            </div>

            {% if user.type=='adult' %}
                <div class="row">
                    <div align="center" class="col">

                        <button style="background: #2c3e50; max-width: 50%; max-height: 100%" class="btn">
                            <a style="color: white"
                               href={{ url_for('adults.choosestud', task_id=task_id, stud_id=reviewed.id) }}>CHOOSE THIS
                                STUDENT</a></button>
                    </div>
                </div>
            {% endif %}

        </div>
    </div>

{% endblock %}

website/templates/user/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block styles %}
{% endblock %}

{% block content %}

    <br/>

    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <img class="img-fluid" style="max-height: 85%; min-width: 100%; margin-bottom: 10vh"
                     src="/static/images/pic/help.png"/>
            </div>
            <div align="top" class="col-6">
                <h1 align="left" style="font-size:48px;">UNITASK</h1>
                <div align="justify">
                    Welcome to the online platform where you can post or look for simple task.<br/><br/>
                    Proceed with the Login if you already have an account, or <a style="color:darkblue"
                                                                                 href={{ url_for('auth.sign_up') }}>Signup
                </a>if you want to create a new account.<br/><br/>
                    If you want to learn more about us click <a style="color:darkblue"
                                                                href={{ url_for('users.about_us') }}>here</a>.<br/><br/>
                </div>

                <form class="login-form" method="POST">
                    <h2 align="center">Login</h2>
                    <div class="form-group">
                        {{ form.email.label }}
                        {{ form.email(class = 'form-control') }}
                    </div>
                    <br/>
                    <div class="form-group">
                        {{ form.password.label }}
                        {{ form.password(class = 'form-control') }}
                    </div>
                    <div align="center">
                        <br/>
                        {{ form.submit(class='btn btn-success btn-lg' ) }}
                        {{ form.hidden_tag() }}
                    </div>
                </form>

            </div>
        </div>

    </div>

{% endblock %}

website/templates/user/logout.html
{% extends "base.html" %} {% block title %}Logout{% endblock %} {% block content %}
    <h1>This is the logout page</h1>
    {{ text }}

{% endblock %}

website/templates/user/personalreviews.html
{% extends "base.html" %} {% block title %}List of Review{% endblock %} {% block content %}
    <br/>
    <h1 align="center">List of review received: </h1>
    <ul class="list-group list-group-flush" id="offers">

        <li class="list-group-item">
            <div>
                {% for recens in user.reviewsreceived %}
                    {{ recens.title }} {{ recens.text }}
                    <br/>
                    Reviewed by:
                    {{ recens.author.first_name }}
                    </div>
                {% endfor %}


        </li>
    </ul>

{% endblock %}

website/templates/user/review.html
{% extends "base.html" %}
{% block title %}Review{% endblock %}
{% block content %}
    <br/>

    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <form class="review-form" style="margin:0; margin-bottom: 10vh" method="POST">
                    <h1 align="left">Review</h1>
                    <div align="justify">
                        Leave a review to the other user. <br/><br/>
                        Tell us how the performance of the task
                        went and if you think that something needs to be improved.
                    </div>
                    <br/>

                    <div align="center">
                        <h2>{{ taskscelta.title }}</h2>
                    </div>
                    <div class="form-group">
                        {{ form.reviewtitle.label }}
                        {{ form.reviewtitle(class = 'form-control') }}
                        {% for error in form.reviewtitle.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                    <br/>
                    <div class="form-group">
                        {{ form.reviewdescription.label }}
                        {{ form.reviewdescription(class = 'form-control') }}
                        {% for error in form.reviewdescription.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                    <div align="center">
                        {{ form.submit(class='btn btn-success m-2') }}
                        {{ form.hidden_tag() }}
                    </div>
                </form>
            </div>
            <div class="col-sm-12 col-md-6">
                <img class="img-fluid" style="max-height: 85%; min-width: 100%" src="/static/images/pic/review.png"/>
            </div>
        </div>
    </div>



{% endblock %}