website/auth.py
# Authentication
from datetime import datetime, timedelta

from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash

from . import db
from .form import LoginForm, SignupForm
from .models import *

auth = Blueprint('auth', __name__)


# We sad clearly that we can accept get and post requests

@auth.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if request.method == 'POST' and form.validate_on_submit():
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                if user.type == 'student':
                    return redirect(url_for('views.home'))
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')
    return render_template("User/login.html", user=current_user, form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign_up', methods=['GET', 'POST'])
def sign_up():
    form = SignupForm()
    if request.method == 'POST' and form.validate_on_submit():

        email = request.form.get('email')
        name = request.form.get('name')
        surname = request.form.get('surname')
        password = request.form.get('password')
        description = request.form.get('description')
        passwordconf = request.form.get('passwordconf')
        type = request.form.get('type')

        user = User.query.filter_by(email=email).first()
        new_user = User
        if type == 'student':
            new_user = Student(email=email, password=generate_password_hash(password, method='sha256'), first_name=name,
                               surname=surname, type=type, description=description)
        elif type == 'adult':
            new_user = Adult(email=email, password=generate_password_hash(password, method='sha256'),
                             first_name=name, surname=surname, type=type, description=description)
        db.session.add(new_user)
        db.session.commit()
        flash('Account created!', category='success')
        login_user(new_user, remember=True)
        if new_user.type == 'student':
            return redirect(url_for('students.offer'))

        return redirect(url_for('views.home'))
    return render_template("User/sign_up.html", user=current_user, form=form)


def riempidb():
    studenti = [
        {'name': "Giacomo", 'surname': "Bertazzolo",
         'description': "I am a studente in IT engineering. I can help you with your computer and all of your electronic devices."},
        {'name': "Valeria", 'surname': "Liuni",
         'description': "I am a student in Engineering and Management at Politecnico di Torino. I love animals and I am ready to help you with them!"},
        {'name': "Caterina", 'surname': "Nassi",
         'description': "I am a student in Education and Formation. I love babies, and I am usually available at the last minute. "},
        {'name': "Oliviero", 'surname': "Vidoni",
         'description': ""},
    ]

    adulti = [
        {'name': "Maria", 'surname': "Bianchi",
         'description': "I am a Manager in a consultancy firm. I have a 4 lovely dogs and I am always looking for someone who can help me with them."},
        {'name': "Paolo", 'surname': "Giorgi",
         'description': "I am a grandfather with 4 amazing nephews. They cannot bear anymore my problems with technology and for this reason I decided to join this community."},
        {'name': "Mario", 'surname': "Rossi",
         'description': "I am a single father whit 3 beautiful children. It may happen that I cannot find someone who can help me with them, especially when there are last minute calls at work."},
    ]

    tasks = [
        {'titolo': "My lovely pet ",
         'descrizione': "I need help with my lovey pet. I'm looking for someone who can take care of her for the afternoon. She is really sweet and docile.",
         'date': "2022-04-23", 'lat': "45.058427", 'lng': "7.655138", 'placeId': "ChIJbZ33QSFtiEcR3Yr-cxhtfDQ",
         'address': "Corso Lione 40"},
        {'titolo': "My PC is not working",
         'descrizione': "I am looking for someone who can fix my computer. My internet connection does not work, can you help me?",
         'date': "2022-05-17", 'lat': "45.07215960121708", 'lng': "7.681296735921444",
         'placeId': "ChIJ-w5Ey3NtiEcRizrB7W-hDNI", 'address': "Via Barbaroux 20"},
        {'titolo': "My grandmother",
         'descrizione': "I am looking for someone who can keep company to my gradmother because she is very lonely.",
         'date': "2022-05-18", 'lat': "45.0602789482421", 'lng': "7.659934143334852",
         'placeId': "ChIJx4qR9SJtiEcRqjxf1yPr6KI", 'address': "Via Marco Polo 38"},
        {'titolo': "My house is a mess!",
         'descrizione': "Hy everyone! I am looking for someone who can help me with my messy house. I am an artist and I have a lot of things in my house that I want to get rid off. Please come and help me! ",
         'date': "2022-04-19", 'lat': "45.074369423709875", 'lng': "7.6562016089387965",
         'placeId': "ChIJXbcpbQJtiEcRayf8ZeGWbPI", 'address': "Corso Ferrucci 12"},
        {'titolo': "Out of town",
         'descrizione': "I am out of town this weekend and my pet sitter is sick! I am looking for a last minute help with my two cats. Please, I am desperate!",
         'date': "2022-03-19", 'lat': "45.031349418202346", 'lng': "7.650670868351874",
         'placeId': "ChIJk67CatsSiEcRwIxAtahQVQg", 'address': "Via Nizza 129"},
        {'titolo': "Moving out",
         'descrizione': "Hello! I am moving out of my house and all of my friends are busy. I am looking for someone that can help me. I have a lot of books and they may be heavy. Thank you!",
         'date': "2022-02-24", 'lat': "45.06489699683761", 'lng': "7.630211069168476",
         'placeId': "ChIJu6nBNJVsiEcRjUReMrrGsg0", 'address': "Via Monginevro 3"},
        {'titolo': "After-school activities",
         'descrizione': "I am looking for someone who can help my children of 12 years old with some math exercises.",
         'date': "2022-03-28", 'lat': "45.07150270339428", 'lng': "7.6755482647576425",
         'placeId': "ChIJbQiBvnJtiEcRuxTkED8C4I8", 'address': "Via Cernaia 8"},
        {'titolo': "Looking for a gardening expert",
         'descrizione': "I am looking for someone who has a passion in gardening that can help me with my plants.",
         'date': "2022-06-28", 'lat': "45.062928866175696", 'lng': "7.701314035921153",
         'placeId': "ChIJ-f-CvJ5yiEcR9YkHqilhGP8", 'address': "Via Umberto Cosmo 6"}
    ]

    ids = {5, 6, 7, 5, 6, 7, 5}

    for studente in studenti:
        mail = studente['name'].lower() + studente['surname'].lower() + '@mail.com'
        user_db = Student(first_name=studente['name'],
                          surname=studente['surname'],
                          email=mail,
                          description=studente['description'],
                          password=generate_password_hash('1234567890', method='sha256'),
                          type='student')
        db.session.add(user_db)
        db.session.commit()

    for adulto in adulti:
        mail = adulto['name'].lower() + adulto['surname'].lower() + '@mail.com'
        user_db = Adult(first_name=adulto['name'],
                        surname=adulto['surname'],
                        email=mail,
                        description=adulto['description'],
                        password=generate_password_hash('1234567890', method='sha256'),
                        type='adult')
        db.session.add(user_db)
        db.session.commit()

    for task in tasks:
        b = 5
        dt = datetime.strptime(task['date'], '%Y-%m-%d')
        de = dt - timedelta(days=4)
        us = User.query.get(b)
        b += 1

        new_offer = Offer(title=task['titolo'], description=task['descrizione'], date_task=dt, amount=10, dateexpire=de,
                          id_adult=us.id, lat=task['lat'], lng=task['lng'], placeId=task['placeId'],
                          address=task['address'])
        db.session.add(new_offer)
        db.session.commit()

    applicant = User.query.get(1)
    offer1 = Offer.query.get(1)
    offer1.applicants.append(applicant)
    applicant2 = User.query.get(2)
    offer1.applicants.append(applicant2)
    print offer1.applicants
    db.session.commit()

website/templates/about_us.html
{% extends "base.html" %}
{% block title %}About us{% endblock %}
{% block content %}


    <div class="container">
        <div class="row">
            <h1 align="center" style="margin:1em;">UNITASK - About us</h1>
            <div align="justify">We are a group of students from <a style="color:darkblue"
                                                                    href="https://www.polito.it/">Politecnico di
                Torino</a>.
                The idea which brought us to UNITASK is mainly related to our condition of students that want to
                have the possibility to earn some money in their free time.
                With our platform we want to give the possibility to people who need help to
                perform simple task, to reach young students as fast as possible.
                <br/><br/></div>
        </div>

        <div class="row">
            <h2 style="margin:1em;" align="center">OUR TEAM</h2>
            <div class="col-4">
                <h3 align="center">Giacomo Bertazzolo</h3>
                <img class="img-fluid m-4" style="box-shadow:1px 1px 1px 1px; border-radius:20em;"
                     src="/static/images/team/Giacomo.png" class="rounded-circle">
                <div align="center">
                    <a href="https://www.linkedin.com/in/giacomo-bertazzolo/"><img class="img-fluid" width="60"
                                                                                   height="60"
                                                                                   src="/static/images/pic/linkedin.png"></a>
                </div>
            </div>
            <div class="col-4">
                <h3 align="center">Pietro Carabelli</h3>
                <img class="img-fluid m-4" style="box-shadow:1px 1px 1px 1px; border-radius:20em;"
                     src="/static/images/team/Pietro.png" class="rounded-circle">
                <div align="center">
                    <a href="https://www.linkedin.com/in/pietro-carabelli-811009198/"><img class="img-fluid" width="60"
                                                                                           height="60"
                                                                                           src="/static/images/pic/linkedin.png"></a>
                </div>
            </div>
            <div class="col-4">
                <h3 align="center">Valeria Liuni</h3>
                <img class="img-fluid m-4" style="box-shadow:1px 1px 1px 1px; border-radius:20em;"
                     src="/static/images/team/Valeria.png" class="rounded-circle">
                <div align="center">
                    <a href="https://www.linkedin.com/in/valeria-liuni-34388520b/"><img class="img-fluid" width="60"
                                                                                        height="60"
                                                                                        src="/static/images/pic/linkedin.png"></a>
                </div>
            </div>
            <div class="col-4" style="padding-top: 25px">
                <h3 align="center">Caterina Nassi</h3>
                <img class="img-fluid m-4" style="box-shadow:1px 1px 1px 1px; border-radius:20em;"
                     src="/static/images/team/Caterina.png" class="rounded-circle">
                <div align="center">
                    <a href="https://www.linkedin.com/in/caterina-nassi-137363182/"><img class="img-fluid" width="60"
                                                                                         height="60"
                                                                                         src="/static/images/pic/linkedin.png"></a>
                </div>
            </div>
            <div class="col-4" style="padding-top: 25px">
                <h3 align="center">Samuele Stasi</h3>
                <img class="img-fluid m-4" style="box-shadow:1px 1px 1px 1px; border-radius:20em;"
                     src="/static/images/team/Samuele.png" class="rounded-circle">
                <div align="center">
                    <a href="https://www.linkedin.com/in/samuele-stasi-02a9611b5/"><img class="img-fluid" width="60"
                                                                                        height="60"
                                                                                        src="/static/images/pic/linkedin.png"></a>
                </div>
            </div>
            <div class="col-4" style="padding-top: 25px">
                <h3 align="center">Oliviero Vidoni</h3>
                <img class="img-fluid m-4" style="box-shadow:1px 1px 1px 1px; border-radius:20em;"
                     src="/static/images/team/Oliviero.png" class="rounded-circle">
                <div align="center">
                    <a href="https://www.linkedin.com/in/oliviero-giacomo-vidoni-15b2261a2/"><img class="img-fluid"
                                                                                                  width="60" height="60"
                                                                                                  src="/static/images/pic/linkedin.png"></a>
                </div>
            </div>
        </div>
    </div>
    <br/><br/>


{% endblock %}

website/templates/autocomp.html
<!DOCTYPE html>
<html>
<head>
    <title>Address Selection</title>
    <link rel="stylesheet" href="static/css/style.css"/>
    <script src="static/app.js"></script>
</head>
<body>
<div class="card-container">
    <div class="panel">
        <div>
            <img class="sb-title-icon" src="https://fonts.gstatic.com/s/i/googlematerialicons/location_pin/v5/24px.svg"
                 alt="">
            <span class="sb-title">Address Selection</span>
        </div>
        <form method="POST">
            <input type="text" placeholder="Address" id="location" name="location"/>
            <input type="text" placeholder="Apt, Suite, etc (optional)"/>
            <input type="text" placeholder="City" id="locality" name="locality"/>
            <div class="half-input-container">
                <input type="text" class="half-input" placeholder="State/Province" id="administrative_area_level_1"
                       name="administrative_area_level_1"/>
                <input type="text" class="half-input" placeholder="Zip/Postal code" id="postal_code"
                       name="postal_code"/>
            </div>
            <input type="text" placeholder="Country" id="country" name="country"/>
            <button type="submit"> Post Task</button>
        </form>
    </div>
</div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDLAnxto2DehvN5I5YdJuyBgEj7CZnX01A&libraries=places&callback=initMap&solution_channel=GMP_QB_addressselection_v1_cAC"
        async defer></script>
</body>
</html>

website/templates/base.html
<!DOCTYPE html>
<html lang="">
<head>

    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link href="/static/css/style.css" rel="stylesheet">
    <link rel="shortcut icon" href="">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- fontawesome -->
    <link href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">



    {% block styles %}
    {% endblock %}


    {% block scripts %} {% endblock %}
    <title> {% block title %}HomePage{% endblock %}</title>
</head>

<body>

<nav class="navbar fixed-top navbar-expand-lg navbar-dark">
    <ul class="navbar-nav mr-auto">
        <li>
            <a style="padding-left:1em;" class="navbar-brand" href="#">
                <img src="/static/images/pic/puzzle.png" width="45" height="45"/>
                UNITASK
            </a></li>
        {% if user.is_authenticated %}
            {% if user.type=='adult' %}
                <li class="nav-item"><a class="nav-link" id="home" href="/">Home</a></li>
                <li class="nav-item"><a class="nav-link" id="posttask" href="{{ url_for('adults.posttask') }}">Post a
                    Task</a></li>
                <li class="nav-item"><a class="nav-link" id="offer" href="{{ url_for('adults.taskpending') }}">Task
                    Pending</a></li>
                <li class="nav-item"><a class="nav-link" id="account" href="{{ url_for('users.account') }}">Account</a>
                </li>
                <li class="nav-item"><a class="nav-link" id="aboutus" href="{{ url_for('users.about_us') }}">About
                    us</a></li>
                <li class="nav-item"><a class="nav-link" id="logout" href="{{ url_for('auth.logout') }}">Logout</a></li>

            {% elif user.type=='student' %}
                <li class="nav-item"><a class="nav-link" id="offer" href="{{ url_for('students.offer') }}">Home</a></li>
                <li class="nav-item"><a class="nav-link" id="maps" href="{{ url_for('students.maps') }}">Maps</a>
                <li class="nav-item"><a class="nav-link" id="applications"
                                        href="{{ url_for('students.listapplications') }}">Your applications</a></li>
                <li class="nav-item"><a class="nav-link" id="account" href="{{ url_for('users.account') }}">Account</a>
                </li>
                <li class="nav-item"><a class="nav-link" id="aboutus" href="{{ url_for('users.about_us') }}">About
                    us</a></li>
                <li class="nav-item"><a class="nav-link" id="logout" href="{{ url_for('auth.logout') }}">Logout</a></li>

            {% endif %}
            </ul>

            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <span style="padding-right:1em;" class="navbar-text d-flex justify-content-end">
                     {{ user.email }}
                       </span>
                </li>

            </ul>

        {% else %}

            <li class="nav-item"><a class="nav-link" id="sign_up" href="{{ url_for('auth.sign_up') }}">Signup</a></li>
            <li class="nav-item"><a class="nav-link" id="login" href="{{ url_for('auth.login') }}">Login</a>
            <li class="nav-item"><a class="nav-link" id="aboutus" href="{{ url_for('users.about_us') }}">About us</a>
            </li>

        {% endif %}
</nav>


{% if form %}
    {% for field in form.errors %}
        {% for error in form.errors[field] %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{ error }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %} {% for category, message in messages %}
        {% if category =='error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% else %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}

{% block content %}

{% endblock %}


<script
        src="https://code.jquery.com/jquery-3.2.1.min.js"
></script>
<script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
></script>
<script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
></script>

<!--Come si importano i file dalla cartella static in cui c'è tutto Javascript -->
<!-- Le parentesi graffe servono per le python expression -->
<script
        type="text/javascript"
        src="{{ url_for('static', filename='index.js') }}"
></script>
<script
        type="text/javascript"
        src="{{ url_for('static', filename='locatorplus.js') }}"
></script>


</body>


{% block footer %}
    <div class="container-fluid mt-5" style="background-color: #f0f0f0">
        <div class="container-lg">
            <div class="row row-cols-md-4 p-3">
                <div class="col-md pb-1 m-auto navbar-light">

                </div>
                <div class="col-md pb-1 m-auto">
                    <h6>Contact Us</h6>
                    <a style="color: #2c3e50" href="mailto:help@unitask.it">help@unitask.it</a>
                </div>
                <div class="col-md pb-1 m-auto">
                    <h6>Follow Us</h6>
                    <img class="img-fluid" style="max-height: 25px; min-width: 25px"
                         src="/static/images/pic/facebook.png"/>
                    <img class="img-fluid" style="max-height: 25px; min-width: 25px"
                         src="/static/images/pic/linkedin.png"/>
                    <img class="img-fluid" style="max-height: 25px; min-width: 25px"
                         src="/static/images/pic/instagram.png"/>
                </div>
                <div class="col-md pb-1">

                </div>
            </div>
        </div>
    </div>
{% endblock footer %}

</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content%}
    <br />
    <h1 align="center">List of Task Posted</h1>
<ul class="list-group list-group-flush" id="offers">
  {% for offer in tasks %}
  <li class="list-group-item">
        {% if offer.isAss!=True %}
     <a href={{ url_for('views.taskscelta', task_id=offer.id) }} >{{ offer.title }}</a> {{ offer.date_task }}
      <div>
        {% for applicant in offer.applicants %}
            {{ applicant.id }}

          {% endfor %}
          <button type="button" class="close" onClick="deleteOffer({{ offer.id }})">
             <span aria-hidden="true">&times;</span>
         </button>
          </div>
          <br/>
        {% endif %}


  </li>
  {% endfor %}
</ul>

{% endblock %}

website/templates/listapplication.html
{% extends "base.html" %} {% block title %}Home Stud{% endblock %} {% block content%}
    <br />
    <h1 align="center">List of Applications Open</h1>
<ul class="list-group list-group-flush" id="offers">
  {% for offer in user.applications %}
      {% if offer.isAss==False %}
  <li class="list-group-item">
     <a href= >{{ offer.title }}</a> {{ offer.date_task }}
      <button> <a href={{ url_for('views.sceltarecensione', task_id=offer.id) }} > Recensisci</a></button>

          <br/>

  </li>
      {% endif %}
  {% endfor %}
</ul>
    <br/>
    <br/>
    <h1 align="center">List of Applications Closed</h1>
<ul class="list-group list-group-flush" id="offers">
  {% for offer in user.applications %}
      {% if offer.isAss==True %}
          {% if offer.scelta==user.id %}
        <li class="list-group-item">
            <a href= >{{ offer.title }}</a> vinta
            {% if offer.isPerf==True %}
            <button> <a href={{ url_for('views.sceltarecensione', task_id=offer.id) }} > Performata e Recensisci</a></button>
            {% endif %}
          <br/>

  </li>
          {% else %}
       <li class="list-group-item">
            <a href= >{{ offer.title }}</a> persa

          <br/>
            {% endif %}
      {% endif %}

  {% endfor %}
</ul>
{% endblock %}

website/templates/login.html
<!-- Abbiamo esteso la pagina base -->
<!-- min.45 cose su come passare le variabili ad html-->
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content%}

<form method = "POST">
    <br />
    <h1 align= "center"> UNITASK </h1>
<body>
Welcome to the online platform where you can post or look for simple task.
Proceed with the Login if you already have an account or <a href="sign_up.html">Signup</a> if you want to create a new account.

If you want to learn more about us click <a href="about_us.html">here</a>.
</body>
<br/>
    <h2 align="center"> Login </h2>
    <div class="form-group">
        {{ form.email.label }}
        {{ form.email(class = 'form-control') }}
        {% for error in form.email.errors %}
            <p>{{ error }}</p>
        {% endfor %}
    </div>
     <div class="form-group">
         {{ form.password.label }}
         {{ form.password(class = 'form-control') }}
         {% for error in form.password.errors %}
             <p>{{ error }}</p>
         {% endfor %}
     </div>
    <br/>
    {{ form.submit(class='btn btn-primary m-2') }}
    {{ form.hidden_tag() }}
</form>
{% endblock %}

website/templates/maps.html
{% extends "base.html" %} {% block scripts %}

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/handlebars/4.7.7/handlebars.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="static/css/locatorplus.css" rel="stylesheet">
    <!--bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="/static/locatorplus.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="/static/app.js"></script>

    <script type="text/javascript">
      function initMap() {
        new LocatorPlus({{ CONFIGURATIONS|tojson }});
      }

    </script>

    {% raw %}
        <script id="locator-result-items-tmpl" type="text/x-handlebars-template">
          {{#each locations}}
            <li class="location-result" data-location-index="{{index}}">
              <button class="select-location">
                <h3 class="task-name">{{title}}</h3>
              </button>
              <h4 class="task-address">{{address1}}{{address2}}</h4>
              {{#if travelDistanceText}}
                <div class="distance">{{travelDistanceText}}</div>
              {{/if}}
                <button type="button" style="background:#2c3e50; color:white; padding:0 12px 0 12px; " class="pick-task"  onClick="window.location.href = '/task/'+{{ task_id }}">Scegli Task</button>
            </li>
          {{/each}}
        </script>
      {% endraw %}

  {% endblock %}

    {% block title %}Locator{% endblock %}

  {% block content%}
    <br />

    <div id="map-container">
    <!--locatior-->

      <div id="locations-panel">
        <div id="locations-panel-list">
          <header>
            <h1 class="search-title">
              <img src="https://fonts.gstatic.com/s/i/googlematerialicons/place/v15/24px.svg"/>
              Find a location near you
            </h1>
            <div class="search-input">
              <input id="location-search-input" placeholder="Enter your address or zip code">
              <div id="search-overlay-search" class="search-input-overlay search">
                <button id="location-search-button">
                  <img class="icon" src="https://fonts.gstatic.com/s/i/googlematerialicons/search/v11/24px.svg" alt="Search"/>
                </button>
              </div>
            </div>
          </header>
          <div class="section-name" id="location-results-section-name">
            All locations
          </div>
          <div class="results">
            <ul id="location-results-list"></ul>
          </div>
        </div>
      </div>

        <!--mappa-->
      <div id="map"></div>
    </div>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDLAnxto2DehvN5I5YdJuyBgEj7CZnX01A&callback=initMap&libraries=places,geometry&solution_channel=GMP_QB_locatorplus_v4_cABD" async defer></script>


{% endblock %}

website/templates/offer.html
{% extends "base.html" %} {% block title %}Apply for Tasks{% endblock %} {% block content%}
 <br />
    <h1 align="center">Apply for a Task</h1>
    <form method="POST">
        <br />
        <h3 align= "center">List of open tasks</h3>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Apply</th>
            </tr>
            </thead>
            {% for offer in tasks %}
            <tbody>
            <tr>
                <th scope="row" value="1"></th>
                <td> <a href={{ url_for('views.taskscelta', task_id=offer.id) }} >{{ offer.title }} </a></td>
                <td>{{ offer.description }}</td>
                <td></td>

            </tr>

            </tbody>
            {% endfor %}
        </table>
    </form>
        {% endblock %}

website/templates/sceltastud.html
{% extends "base.html" %} {% block title %}Scelta Studente{% endblock %} {% block content%}
    <br />
    <h1 align="center">Scegli studente</h1>
<ul class="list-group list-group-flush" id="offers">

  <li class="list-group-item">
    <h3>{{ taskscelta.title }}</h3>
  <br/>
      <div>{{ taskscelta.description }}</div>
      <div>
      <br/>
      <h3>Applicants:</h3>
      <br/>
        {% for applicant in taskscelta.applicants %}
            <div>
            <a href={{ url_for('views.vedirecensioni', stud_id=applicant.id) }} > {{ applicant.id }} {{ applicant.first_name }} {{ applicant.surname }}</a>
            <button class="btn btn-sm btn-outline-primary" > <a href={{ url_for('views.sceglistud', task_id=taskscelta.id, stud_id=applicant.id) }} >Scegli questo studente </a></button>

            </div>
            <br/>
          {% endfor %}
      </div>


  </li></ul>

{% endblock %}